-- 1. Create crosscheck_sample table
CREATE TABLE IF NOT EXISTS public.crosscheck_sample (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    msnv text,
    rpro text,
    customer text,
    brand text,
    mold text,
    po_qty numeric,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.crosscheck_sample ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Access" ON public.crosscheck_sample FOR SELECT TO anon USING (true);
CREATE POLICY "Public Insert Access" ON public.crosscheck_sample FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Public Update Access" ON public.crosscheck_sample FOR UPDATE TO anon USING (true);
CREATE POLICY "Public Delete Access" ON public.crosscheck_sample FOR DELETE TO anon USING (true);

-- 2. Create test_lab table
CREATE TABLE IF NOT EXISTS public.test_lab (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    msnv text,
    rpro text,
    customer text,
    brand text,
    mold text,
    po_qty numeric,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.test_lab ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Access" ON public.test_lab FOR SELECT TO anon USING (true);
CREATE POLICY "Public Insert Access" ON public.test_lab FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Public Update Access" ON public.test_lab FOR UPDATE TO anon USING (true);
CREATE POLICY "Public Delete Access" ON public.test_lab FOR DELETE TO anon USING (true);

-- 3. Register page config
INSERT INTO public.system_config (id, value, description)
VALUES ('status_internal-checker.html', 'ON', 'Status of Internal Checker Page')
ON CONFLICT (id) DO NOTHING;
