
-- QUAN TRỌNG: Hãy chạy lệnh này trong Supabase Dashboard (https://supabase.com/dashboard/project/ixdtdrbytwdmnlqgunzu/editor)
-- KHÔNG chạy trong Vercel Dashboard vì ứng dụng đang kết nối tới dự án Supabase.

-- 1. Xóa nếu đã tồn tại để làm sạch dữ liệu cũ
DROP TABLE IF EXISTS public.supplement_counting;

-- 2. Tạo bảng với cấu trúc chuẩn
CREATE TABLE IF NOT EXISTS public.supplement_counting (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rpro text NOT NULL,
    section text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    scan_date date DEFAULT CURRENT_DATE NOT NULL
);

-- 3. Tạo ràng buộc chống trùng lặp
ALTER TABLE public.supplement_counting 
ADD CONSTRAINT unique_rpro_section_date UNIQUE (rpro, section, scan_date);

-- 4. Phân quyền truy cập cho ứng dụng web (Rất quan trọng)
ALTER TABLE public.supplement_counting ENABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE public.supplement_counting TO anon, authenticated, service_role;

DROP POLICY IF EXISTS "Public Full Access" ON public.supplement_counting;
CREATE POLICY "Public Full Access" ON public.supplement_counting 
FOR ALL TO anon USING (true) WITH CHECK (true);

-- 5. Lệnh kiểm tra: Sau khi chạy xong, hãy nhấn Run lệnh dưới đây:
-- SELECT * FROM public.supplement_counting;
