-- SQL to create the powerapp table in Supabase
-- Run this in the Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.powerapp (
    "STT" bigint PRIMARY KEY,
    "SO" text,
    "PRO ODER" text,
    "Brand Code" text,
    "CUSTOMERS" text,
    "#MOLDED" text,
    "#MOLD" text,
    "Total Qty" numeric,
    "RECEIVED (MATERIAL)" text,
    "RECEIVED (LOGO)" text,
    "Laminating (Pro)" text,
    "Prefitting (Pro)" text,
    "Slipting (Pro)" text,
    "THĂNG HOA" text,
    "SUB" text,
    "Molding Pro (IN)" text,
    "Molding Pro" text,
    "IN lean Line (Pro)" text,
    "Out lean Line (Pro)" text,
    "IN lean Line (MACHINE)" text,
    "STORED" text,
    "Finish date" text,
    "PPC Confirm" text,
    "STATUS" text,
    "BOM" text,
    "#Last" text,
    "GENDER" text,
    "PU" text,
    "PU DESCRIPTION" text,
    "DL PU" numeric,
    "PU2" text,
    "PU2 DESCRIPTION" text,
    "DL PU2" text,
    "PU3" text,
    "PU3 DESCRIPTION" text,
    "DL PU3" text,
    "FB" text,
    "FB DESCRIPTION" text,
    "DL FB" numeric,
    "LOGO" text,
    "LOGO DESCRIPTION" text,
    "DL LOGO" numeric,
    "CODE LOGO2" text,
    "Description LOGO2" text,
    "DL LOGO2" text,
    "CODE LOGO3" text,
    "Description LOGO3" text,
    "DL LOGO3" text,
    "CODE LOGO4" text,
    "Description LOGO4" text,
    "DL LOGO4" text,
    "3" text,
    "3.5" text,
    "4" text,
    "4.5" text,
    "5" text,
    "5.5" text,
    "6" text,
    "6.5" text,
    "7" text,
    "7.5" text,
    "8" text,
    "8.5" text,
    "9" text,
    "9.5" text,
    "10" text,
    "10.5" text,
    "11" text,
    "11.5" text,
    "12" text,
    "12.5" text,
    "13" text,
    "13.5" text,
    "14" text,
    "14.5" text,
    "15" text,
    "15.5" text,
    "16" text,
    "16.5" text,
    "17" text,
    "17.5" text,
    "18" text,
    "18.5" text,
    "19" text,
    "19.5" text,
    "20" text,
    "20.5" text,
    "21" text,
    "21.5" text,
    "22" text,
    "22.5" text,
    "23" text,
    "23.5" text,
    "24" text,
    "24.5" text,
    "25" text,
    "25.5" text,
    "26" text,
    "26.5" text,
    "27" text,
    "27.5" text,
    "28" text,
    "28.5" text,
    "29" text,
    "29.5" text,
    "30" text,
    "30.5" text,
    "31" text,
    "31.5" text,
    "32" text,
    "32.5" text,
    "33" text,
    "33.5" text,
    "34" text,
    "34.5" text,
    "35" text,
    "35.5" text,
    "36" text,
    "36.5" text,
    "37" text,
    "37.5" text,
    "38" text,
    "38.5" text,
    "39" text,
    "39.5" text,
    "40" text,
    "40.5" text,
    "41" text,
    "41.5" text,
    "42" text,
    "42.5" text,
    "43" text,
    "43.5" text,
    "44" text,
    "44.5" text,
    "45" text,
    "45.5" text,
    "46" text,
    "46.5" text,
    "47" text,
    "47.5" text,
    "48" text,
    "48.5" text,
    "49" text,
    "49.5" text,
    "50" text,
    "LAMINATION MACHINE (PLAN)" text,
    "LEANLINE PLAN" text,
    "Delay-Urgent" text,
    "LAMINATION MACHINE (REALTIME)" text,
    "LEANLINE (REALTIME)" text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==========================================
-- CREATE THE supplement TABLE
-- ==========================================

CREATE TABLE IF NOT EXISTS public.supplement (
    rpro text PRIMARY KEY,
    so text,
    customers text,
    gender text,
    mold text,
    pu text,
    fabric text,
    bom text,
    total numeric DEFAULT 0,
    remark text,
    remark2 text,
    -- Size columns (normalized: size_3, size_3_5, etc.)
    size_3 numeric DEFAULT 0, size_3_5 numeric DEFAULT 0, size_4 numeric DEFAULT 0, size_4_5 numeric DEFAULT 0, size_5 numeric DEFAULT 0,
    size_5_5 numeric DEFAULT 0, size_6 numeric DEFAULT 0, size_6_5 numeric DEFAULT 0, size_7 numeric DEFAULT 0, size_7_5 numeric DEFAULT 0,
    size_8 numeric DEFAULT 0, size_8_5 numeric DEFAULT 0, size_9 numeric DEFAULT 0, size_9_5 numeric DEFAULT 0, size_10 numeric DEFAULT 0,
    size_10_5 numeric DEFAULT 0, size_11 numeric DEFAULT 0, size_11_5 numeric DEFAULT 0, size_12 numeric DEFAULT 0, size_12_5 numeric DEFAULT 0,
    size_13 numeric DEFAULT 0, size_13_5 numeric DEFAULT 0, size_14 numeric DEFAULT 0, size_14_5 numeric DEFAULT 0, size_15 numeric DEFAULT 0,
    size_15_5 numeric DEFAULT 0, size_16 numeric DEFAULT 0, size_16_5 numeric DEFAULT 0, size_17 numeric DEFAULT 0, size_17_5 numeric DEFAULT 0,
    size_18 numeric DEFAULT 0, size_18_5 numeric DEFAULT 0, size_19 numeric DEFAULT 0, size_19_5 numeric DEFAULT 0, size_20 numeric DEFAULT 0,
    size_20_5 numeric DEFAULT 0, size_21 numeric DEFAULT 0, size_21_5 numeric DEFAULT 0, size_22 numeric DEFAULT 0, size_22_5 numeric DEFAULT 0,
    size_23 numeric DEFAULT 0, size_23_5 numeric DEFAULT 0, size_24 numeric DEFAULT 0, size_24_5 numeric DEFAULT 0, size_25 numeric DEFAULT 0,
    size_25_5 numeric DEFAULT 0, size_26 numeric DEFAULT 0, size_26_5 numeric DEFAULT 0, size_27 numeric DEFAULT 0, size_27_5 numeric DEFAULT 0,
    size_28 numeric DEFAULT 0, size_28_5 numeric DEFAULT 0, size_29 numeric DEFAULT 0, size_29_5 numeric DEFAULT 0, size_30 numeric DEFAULT 0,
    size_30_5 numeric DEFAULT 0, size_31 numeric DEFAULT 0, size_31_5 numeric DEFAULT 0, size_32 numeric DEFAULT 0, size_32_5 numeric DEFAULT 0,
    size_33 numeric DEFAULT 0, size_33_5 numeric DEFAULT 0, size_34 numeric DEFAULT 0, size_34_5 numeric DEFAULT 0, size_35 numeric DEFAULT 0,
    size_35_5 numeric DEFAULT 0, size_36 numeric DEFAULT 0, size_36_5 numeric DEFAULT 0, size_37 numeric DEFAULT 0, size_37_5 numeric DEFAULT 0,
    size_38 numeric DEFAULT 0, size_38_5 numeric DEFAULT 0, size_39 numeric DEFAULT 0, size_39_5 numeric DEFAULT 0, size_40 numeric DEFAULT 0,
    size_40_5 numeric DEFAULT 0, size_41 numeric DEFAULT 0, size_41_5 numeric DEFAULT 0, size_42 numeric DEFAULT 0, size_42_5 numeric DEFAULT 0,
    size_43 numeric DEFAULT 0, size_43_5 numeric DEFAULT 0, size_44 numeric DEFAULT 0, size_44_5 numeric DEFAULT 0, size_45 numeric DEFAULT 0,
    size_45_5 numeric DEFAULT 0, size_46 numeric DEFAULT 0, size_46_5 numeric DEFAULT 0, size_47 numeric DEFAULT 0, size_47_5 numeric DEFAULT 0,
    size_48 numeric DEFAULT 0, size_48_5 numeric DEFAULT 0, size_49 numeric DEFAULT 0, size_49_5 numeric DEFAULT 0, size_50 numeric DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.supplement ENABLE ROW LEVEL SECURITY;

-- Policies for public access (Anon)
CREATE POLICY "Public Read Access" ON public.supplement FOR SELECT TO anon USING (true);
CREATE POLICY "Public Insert Access" ON public.supplement FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Public Update Access" ON public.supplement FOR UPDATE TO anon USING (true);
CREATE POLICY "Public Delete Access" ON public.supplement FOR DELETE TO anon USING (true);
