-- SQL to create the powerapp table in Supabase
-- Run this in the Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.powerapp (
    "STT" bigint PRIMARY KEY,
    "SO" text,
    "PRO ODER" text,
    "Brand Code" text,
    "CUSTOMERS" text,
    "#MOLDED" text,
    "#MOLD" text,
    "Total Qty" numeric,
    "RECEIVED (MATERIAL)" text,
    "RECEIVED (LOGO)" text,
    "Laminating (Pro)" text,
    "Prefitting (Pro)" text,
    "Slipting (Pro)" text,
    "THĂNG HOA" text,
    "SUB" text,
    "Molding Pro (IN)" text,
    "Molding Pro" text,
    "IN lean Line (Pro)" text,
    "Out lean Line (Pro)" text,
    "IN lean Line (MACHINE)" text,
    "STORED" text,
    "Finish date" text,
    "PPC Confirm" text,
    "STATUS" text,
    "BOM" text,
    "#Last" text,
    "GENDER" text,
    "PU" text,
    "PU DESCRIPTION" text,
    "DL PU" numeric,
    "PU2" text,
    "PU2 DESCRIPTION" text,
    "DL PU2" text,
    "PU3" text,
    "PU3 DESCRIPTION" text,
    "DL PU3" text,
    "FB" text,
    "FB DESCRIPTION" text,
    "DL FB" numeric,
    "LOGO" text,
    "LOGO DESCRIPTION" text,
    "DL LOGO" numeric,
    "CODE LOGO2" text,
    "Description LOGO2" text,
    "DL LOGO2" text,
    "CODE LOGO3" text,
    "Description LOGO3" text,
    "DL LOGO3" text,
    "CODE LOGO4" text,
    "Description LOGO4" text,
    "DL LOGO4" text,
    "3" text,
    "3.5" text,
    "4" text,
    "4.5" text,
    "5" text,
    "5.5" text,
    "6" text,
    "6.5" text,
    "7" text,
    "7.5" text,
    "8" text,
    "8.5" text,
    "9" text,
    "9.5" text,
    "10" text,
    "10.5" text,
    "11" text,
    "11.5" text,
    "12" text,
    "12.5" text,
    "13" text,
    "13.5" text,
    "14" text,
    "14.5" text,
    "15" text,
    "15.5" text,
    "16" text,
    "16.5" text,
    "17" text,
    "17.5" text,
    "18" text,
    "18.5" text,
    "19" text,
    "19.5" text,
    "20" text,
    "20.5" text,
    "21" text,
    "21.5" text,
    "22" text,
    "22.5" text,
    "23" text,
    "23.5" text,
    "24" text,
    "24.5" text,
    "25" text,
    "25.5" text,
    "26" text,
    "26.5" text,
    "27" text,
    "27.5" text,
    "28" text,
    "28.5" text,
    "29" text,
    "29.5" text,
    "30" text,
    "30.5" text,
    "31" text,
    "31.5" text,
    "32" text,
    "32.5" text,
    "33" text,
    "33.5" text,
    "34" text,
    "34.5" text,
    "35" text,
    "35.5" text,
    "36" text,
    "36.5" text,
    "37" text,
    "37.5" text,
    "38" text,
    "38.5" text,
    "39" text,
    "39.5" text,
    "40" text,
    "40.5" text,
    "41" text,
    "41.5" text,
    "42" text,
    "42.5" text,
    "43" text,
    "43.5" text,
    "44" text,
    "44.5" text,
    "45" text,
    "45.5" text,
    "46" text,
    "46.5" text,
    "47" text,
    "47.5" text,
    "48" text,
    "48.5" text,
    "49" text,
    "49.5" text,
    "50" text,
    "LAMINATION MACHINE (PLAN)" text,
    "LEANLINE PLAN" text,
    "Delay-Urgent" text,
    "LAMINATION MACHINE (REALTIME)" text,
    "LEANLINE (REALTIME)" text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Optional, but recommended)
-- ALTER TABLE public.powerapp ENABLE ROW LEVEL SECURITY;

-- Create policy to allow read access for everyone (since it's a public dashboard)
-- CREATE POLICY "Public Read Access" 
-- ON public.powerapp FOR SELECT 
-- TO anon, authenticated 
-- USING (true);

-- Create policy to allow insert/update/delete for authenticated or anon (assuming the script uses the same key)
-- Note: In a real production environment, you should only allow write access to a service_role or specific user.
-- Since the current setup uses the anon key for everything (based on script.js), we allow anon to write for now.
-- Or better, ensure the sync script runs in an environment where it can bypass RLS or has a policy.
-- Given the user provided an anon key in script.js, we'll allow anon write for this table to make the script work immediately.
-- CREATE POLICY "Public Write Access"
-- ON public.powerapp FOR INSERT
-- TO anon
-- WITH CHECK (true);

-- CREATE POLICY "Public Update Access"
-- ON public.powerapp FOR UPDATE
-- TO anon
-- USING (true);

-- CREATE POLICY "Public Delete Access"
-- ON public.powerapp FOR DELETE
-- TO anon
-- USING (true);
